# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syferadmin', '0002_view_report_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncountry',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='syferadmin.Region'),
        ),
    ]
